### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by kadirgun** [atomjoy/proton#1]
https://github.com/atomjoy/proton/blob/cfa9c5cccb0034c1915ad62c094a6ffa905e6a34/resources/views/components/email.blade.php#L40-L41

To work properly on mobile devices

```css
max-width: 640px;
```

**Comment by atomjoy** [comment]
RWD works ok in the browser, if you don't know how it works, don't write nonsense.

**Comment by atomjoy** [comment]
And if you want to improve something, you can always change the content of the template:

`
# Edit package email views in resources/views/vendor/proton
php artisan vendor:publish --tag=proton-views --force
`

**Comment by kadirgun** [comment]
Dude, I made a suggestion that might help your project. That doesn't mean you have to be rude.

**Comment by atomjoy** [comment]
To give suggestions, you need to know what you are writing or talking about. And from what you wrote, it's clear that you have no idea about the basics of CSS. Go waste your time somewhere else. Regards.

**Comment by kadirgun** [comment]
You must have psychological problems 😂

**Comment by atomjoy** [comment]
You're the one who talks to people like an idiot and makes a fool of yourself.
